name: CMake on multiple platforms

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        include:
          - os: windows-latest
            generator: "Ninja"
          - os: ubuntu-latest
            generator: "Ninja"

    steps:
    - uses: actions/checkout@v4

    - name: Set up MSYS2 for Windows
      if: matrix.os == 'windows-latest'
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          base-devel
          mingw-w64-ucrt-x86_64-toolchain
          mingw-w64-x86_64-cmake

    - name: Set up Ninja
      uses: juliankern/actions-setup-ninja@v2
      if: matrix.os == 'windows-latest' || matrix.os == 'ubuntu-latest'

    - name: Install Ninja for Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install ninja-build

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: |
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
              -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
              -G ${{ matrix.generator }}
              -A x64  # For Windows builds
              -S ${{ github.workspace }}
      if: matrix.os == 'windows-latest'

    - name: Configure CMake
      run: |
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
              -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
              -G ${{ matrix.generator }}
              -S ${{ github.workspace }}
      if: matrix.os == 'ubuntu-latest'

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --build-config ${{ matrix.build_type }}
